#
# JDBC properties
#
spring.datasource.url=jdbc:mysql://localhost:3306/secure_users_directory?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Philiptsk793!

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable logging at DEBUG level for your application
logging.level.root=INFO
logging.level.org.springframework=DEBUG
logging.level.myy803.springboot.sb_tutorial_7_signup_signin=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true